trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

stages:
 - stage: CreateDeploymentArtifacts
   displayName: Create Deployment Artifacts
   jobs:
    - job: CreateDeploymentArtifacts
      displayName: Create Deployment Artifacts
      steps:
      - task: DotNetCoreCLI@2
        name: 'Build'
        inputs:
          command: 'build'
          projects: 'AppServiceTestApi.sln'
      - task: DotNetCoreCLI@2
        name: 'Test'
        inputs:
          command: 'test'
          projects: 'AppServiceTestApi.sln'
      - task: DotNetCoreCLI@2
        name: 'Publish'
        inputs:
          command: publish
          publishWebProjects: true
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'buildArtifact'
          publishLocation: 'Container'

 - stage: Deploy
   displayName: Deploy
   jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      environment: 'app-service-test'
      strategy:
        runOnce:
          deploy:
            steps:
             - task: DownloadBuildArtifacts@0
               inputs:
                 buildType: 'current'
                 downloadType: 'single'
                 artifactName: 'buildArtifact'
                 downloadPath: '$(System.ArtifactsDirectory)'

