trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

stages:
 - stage: CreateDeploymentArtifacts
   displayName: Create Deployment Artifacts
   jobs:
    - job: CreateDeploymentArtifacts
      displayName: Create Deployment Artifacts
      steps:
      - task: DotNetCoreCLI@2
        name: 'Build'
        inputs:
          command: 'build'
          projects: 'AppServiceTestApi.sln'

      - task: DotNetCoreCLI@2
        name: 'Test'
        inputs:
          command: 'test'
          projects: 'AppServiceTestApi.sln'