trigger:
  - master

pr:
  - master

pool:
  vmImage: 'windows-latest'

stages:
 - stage: CreateDeploymentArtifacts
   displayName: Create Deployment Artifacts
   jobs:
    - job: CreateDeploymentArtifacts
      displayName: Create Deployment Artifacts
      steps:
      - task: DotNetCoreCLI@2
        name: 'Build'
        inputs:
          command: 'build'
          projects: 'AppServiceTestApi.sln'
      - task: DotNetCoreCLI@2
        name: 'Test'
        inputs:
          command: 'test'
          projects: 'AppServiceTestApi.sln'
      - task: DotNetCoreCLI@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        name: 'Publish'
        inputs:
          command: publish
          publishWebProjects: true
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
      - task: PublishBuildArtifacts@1
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'buildArtifact'
          publishLocation: 'Container'

 - stage: Deploy
   displayName: Deploy
   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
   jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      environment: 'app-service-test'
      strategy:
        runOnce:
          deploy:
            steps:
             - task: DownloadBuildArtifacts@0
               inputs:
                 buildType: 'current'
                 downloadType: 'single'
                 artifactName: 'buildArtifact'
                 downloadPath: '$(System.ArtifactsDirectory)'
             - task: AzureRmWebAppDeployment@4
               inputs:
                 ConnectionType: 'AzureRM'
                 azureSubscription: 'deploy-test-app-service'
                 appType: 'webApp'
                 WebAppName: 'joel-test-app-service-1'
                 package: '$(System.ArtifactsDirectory)/**/*.zip'